// examples/react/src/App.tsx
import { Outlet, RouterProvider, createBrowserRouter } from "react-router-dom";
import Todo from "./routes/Todo";
import Home from "./routes/Home";
import ErrorPage from "./ErrorPage";
import Navbar from "./Navbar";

function RootLayout() {
  return (
    <div id="app">
      <Navbar />
      <main className="app-main-content">
        <Outlet />
      </main>
    </div>
  );
}

const router = createBrowserRouter([
  {
    path: "/",
    element: <RootLayout />,
    errorElement: <ErrorPage />,
    children: [
      {
        path: "/",
        element: <Home />,
      },
      {
        path: "todo",
        element: <Todo />,
      },
    ],
  },
]);

function App() {
  return <RouterProvider router={router} fallbackElement={<p>Loading...</p>} />;
}

export default App;

// examples/solid-js/src/App.tsx
import { ParentComponent, lazy } from "solid-js";
import { Router, Route } from "@solidjs/router";
import Navbar from "./Navbar";

const Home = lazy(() => import("./pages/Home"));
const TodoList = lazy(() => import("./pages/TodoList"));
const TodoListEditor = lazy(() => import("./pages/TodoListEditor"));

const AppLayout: ParentComponent = (props) => {
  return (
    <div id="app">
      <Navbar />
      <main class="app-main-content">{props.children}</main>
    </div>
  );
};

function App() {
  return (
    <Router root={AppLayout}>
      <Route path="/" component={Home} />
      <Route path="/todo" component={TodoList} />
      <Route path="/todoEdit" component={TodoListEditor} />
    </Router>
  );
}

export default App;
